### ISSUE TITLE
[Feature request] Would be nice if output configuration could be used directly in API

### ISSUE THREAD

**Issue by SEYentl** [pimcore/output-data-config-toolkit#12]
**Description:**
When creating an output data configuration with the name "Magento" it would be nice that the api with the name of the output configuration name would get the data as configured in the data configuration tool.

**Example:**
1) Make an output configuration with the name "Magento".
2) Configure the output configuration for this consumer.
3) Query the api for a product with the name of the configuration as a parameter.
YOUR-DOMAIN/webservice/rest/**configuration/magento**/object/id/9253?apikey=[KEY]
4) The data is provided by the api the way it was configured in the configuration tool.

**Comment by fashxp** [comment]
there is something on the way for that ... see https://github.com/pimcore/pimcore/issues/3065
so stay tuned.

**Comment by SEYentl** [comment]
@fashxp Thanks, will follow that issue :)

**Comment by fashxp** [comment]
see https://github.com/pimcore/data-hub
