### ISSUE TITLE
Compatibility with pimcore 6.6.x

### ISSUE THREAD

**Issue by moiashvin** [pimcore/output-data-config-toolkit#25]
Hi, when you plan to make toolkit compatible for pimcore 6.6.x.
At the moment, an error is displayed.
`Cannot autowire argument $eventDispatcher of "OutputDataConfigToolkitBundle\Controller\AdminController::saveOutputConfigAction()": it references class "Symfony\Component\EventDispatcher\EventDispatcher" but no such service exists. Try changing the type-hint to one of its parents: interface "Symfony\Component\EventDispatcher\EventDispatcherInterface", or interface "Symfony\Contracts\EventDispatcher\EventDispatcherInterface".

Server threw exception - could not perform action. Please reload the admin interface and try again.`

**Comment by fashxp** [comment]
hmm, when do you get this error message? 
should be compatible with pimcore 6.6.x ... at least the demo works too.

**Comment by fashxp** [comment]
probably switching to eventdispatcherinterface fixes your problem.
