### ISSUE TITLE
Attempted to call an undefined method named "getFullPath" of class "Pimcore\Model\Element\ElementDescriptor".

### ISSUE THREAD

**Issue by kumar2112** [pimcore/output-data-config-toolkit#30]
Hi All
I am facing this issue when i select classess from out put config and trying to save it. 
IT throws the below exception
**Attempted to call an undefined method named "getFullPath" of class "Pimcore\Model\Element\ElementDescriptor".**

**Comment by dvesh3** [comment]
duplicate #31
