### ISSUE TITLE
Attempted to call an undefined method named "getFullPath" of class

### ISSUE THREAD

**Issue by kumar2112** [pimcore/output-data-config-toolkit#31]
Hi I am getting this error when i click on save . where output config is  defined

![image](https://user-images.githubusercontent.com/12470739/116187503-465bc980-a743-11eb-9d94-2fd228c1da71.png)

**Comment by kumar2112** [comment]
> @kumar2112 could you please share more information like Pimcore version, stack trace? thanks!

Yes version is  6.8.6. 
On My local its workking fine . but on server its throwing above exception

**Comment by dvesh3** [comment]
@kumar2112 could you please share complete stack trace? thanks!

**Comment by dvesh3** [comment]
Closed due to inactivity. Please feel free to discuss further 😉

**Comment by kumar2112** [comment]
I have attached the stacktrace

**Comment by kumar2112** [comment]
@dvesh3 please check i have attached the statck trace
