### ISSUE TITLE
Support for object bricks

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/output-data-config-toolkit#4]
I have a class with an object brick field. In the output channel configuration the assigned bricks are not selectable. Did I miss a setting or isn't this possible at the moment?

**Comment by fashxp** [comment]
hmm, that should be perfectly possible ... see a screenshot in of our demo advanced

![image](https://user-images.githubusercontent.com/8792145/34959347-6a34c2a2-fa36-11e7-8887-09b46cdcbe08.png)
